### ISSUE TITLE
Can't deploy dashboard 

### ISSUE THREAD

**Issue by CyrilParisot** [aws-samples/visualize-iam-access-analyzer-policy-validation-findings#1]
Follow the blog on a Control Tower standard organization (main region eu-west-3)

When trying to deploy dashboard (from security account same as quicksight), I get Unrecognized resource types: [AWS::QuickSight::DataSet]

`make deploy-dashboard-hub aws-region=eu-west-3 quicksight-user-arn=<userarn> `
An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: Unrecognized resource types: [AWS::QuickSight::DataSet]
make: *** [deploy-dashboard-hub] Error 254

same using CloudFormation template directly 
error creating changeset: Template format error: Unrecognized resource types: [AWS::QuickSight::DataSet]

**Comment by CyrilParisot** [comment]
Issue is link to eu-west-3 region that seems to not support yet all quicksight resources  (or its from cloudformation support of resources)

deploy on eu-est-1 encounter an error on creation 
AccessAnalyzerFindingsTemplate trigger TemplateError(type=ACCESS_DENIED, message=You do not have permissions to access the source)]
the source template propose seams not accessible 

Minor improvement could be :
 - the cleaning part could improve to also empty bucket first (script or CustomResource  ;) ) 
- pS3BucketName should be randomized to give possibility to retry without failure 
- add region that support this artefact

**Comment by MostefaB** [comment]
Thank you for the feedback and the improvement ideas.
We are looking into your issue and will suggest a fix if necessary.

**Comment by MostefaB** [comment]
Issue fixed with [this commit](https://github.com/aws-samples/visualize-iam-access-analyzer-policy-validation-findings/commit/d144581ed4dcd69ae2682bc25a9456f4d4e543fb#diff-646658d980f1666073ee366f038808a421fe03cfbce484b4d9e1fbbcfb402c04R111). Please re-open it if you encounter any difficulty deploying the implementation.

**Comment by CyrilParisot** [comment]
thanks !
