### ISSUE TITLE
Cross-Account Policy Validation not possible to Publish to SQS in Hub - KMS Policy

### ISSUE THREAD

**Issue by mtrampic** [aws-samples/visualize-iam-access-analyzer-policy-validation-findings#2]
Following KMS Policy breaks cross account functionality.

https://github.com/aws-samples/visualize-iam-access-analyzer-policy-validation-findings/blob/274e4ed0e2ee6ded7a985cd5e7cd130bd1745eaa/multi-account-deployment/hub.template.yaml#L127-L128

You get error like this in spoke account:

```
{
    "level": "ERROR",
    "location": "send_message_to_sqs_queue:55",
    "message": "An error occured: An error occurred (KMS.AccessDeniedException) when calling the SendMessage operation: null (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: {#MASKED#}; Proxy: null)",
    "timestamp": "2023-02-19 12:53:04,699+0000",
    "service": "access_analyzer_list_policies",
    "cold_start": true,
    "function_name": "access-analyzer-list-iam-policy",
    "function_memory_size": "1024",
    "function_arn": "arn:aws:lambda:us-east-1:{#MASKED#}:function:access-analyzer-list-iam-policy",
    "function_request_id": "#MASKED#}:",
    "xray_trace_id": "{#MASKED#}"
}
```

Lambda function also doesn't contain path /access-analyzer if intention was to have something like:
```yaml
  StringLike:
    aws:PrincipalArn: !Sub arn:${AWS::Partition}:iam::*:role/access-analyzer/*
```
quick solution was removing from KMS policy this condition.

**Comment by Mostefa-Brougui-AWS** [comment]
Issue reproduced and fixed in [this commit](https://github.com/aws-samples/visualize-iam-access-analyzer-policy-validation-findings/commit/c07e84656bac0df048d489c7af001bbcac025d3c).

**Comment by MostefaB** [comment]
Issue fixed in [this commit](https://github.com/aws-samples/visualize-iam-access-analyzer-policy-validation-findings/commit/c07e84656bac0df048d489c7af001bbcac025d3c).
